<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: IKER MARTIN BURUAGA
Curso: DAW1
Fecha: 17/03/2025
Ejercicio: EJERCICIO 1
-->

<!DOCTYPE agenda [
    <!ELEMENT agenda (nombre, apellido, apellido, telefono, fecha_nacimiento, lugar_nacimiento)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT fecha_nacimiento (anio, mes, dia)>
    <!ELEMENT anio (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT lugar_nacimiento (pais, ciudad, localidad)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT localidad (#PCDATA)>
]>

<!--Definicion de una agenda-->
<agenda>
    <nombre>Antonio</nombre>
    <apellido>Sánchez</apellido>
    <apellido>Pérez</apellido>
    <telefono>666555444</telefono>
    <!--Definicion de una fecha de nacimiento-->
    <fecha_nacimiento>
        <anio>2000</anio>
        <mes>01</mes>
        <dia>20</dia>
    </fecha_nacimiento>

    <!--Definicion de un lugar de nacimiento-->
    <lugar_nacimiento>
        <pais>España</pais>
        <ciudad>Madrid</ciudad>
        <localidad>Getafe</localidad>
    </lugar_nacimiento>
</agenda>